apiVersion: apps/v1
kind: Deployment
metadata:
  name: fx-service
  namespace: fincore
  labels:
    app: fx-service
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fx-service
  template:
    metadata:
      labels:
        app: fx-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8084"
    spec:
      containers:
        - name: fx-service
          image: fincore/fx-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-fx:5432/fx_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fx-db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fx-db-secret
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:29092
            - name: SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
            - name: FX_PROVIDER_PRIMARY_URL
              valueFrom:
                secretKeyRef:
                  name: fx-provider-secret
                  key: primary-url
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
---
apiVersion: v1
kind: Service
metadata:
  name: fx-service
  namespace: fincore
spec:
  selector:
    app: fx-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP